services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: commit-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://commit_user:commit_password@postgres:5432/commit_dev
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=commit_dev_secret_key_12345
      - REFRESH_TOKEN_SECRET=commit_refresh_secret_67890
      - LOG_LEVEL=debug
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
    command: npm run db
    restart: unless-stopped
    networks:
      - commit-network
  postgres:
    image: postgres:15-alpine
    container_name: commit-postgres
    environment:
      POSTGRES_DB: commit_dev
      POSTGRES_USER: commit_user
      POSTGRES_PASSWORD: commit_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U commit_user -d commit_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - commit-network

  redis:
    image: redis:7-alpine
    container_name: commit-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - commit-network

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    container_name: commit-mobile
    environment:
      - NODE_ENV=development
      - EXPO_PUBLIC_API_URL=http://backend:3000
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    tty: true
    ports:
      - "8080"  # Web interface (Docker auto-assigns host port)
      - "8081:8081"  # Metro bundler
      - "19001-19002:19001-19002"  # Expo DevTools
      - "19006"  # Expo web DevTools (Docker auto-assigns host port)
    volumes:
      - ./mobile:/opt/react_native_app:delegated
      - mobile_node_modules:/opt/react_native_app/node_modules
    depends_on:
      backend:
        condition: service_started
    networks:
      - commit-network
    healthcheck:
      disable: true

  # Optional: Redis Commander for debugging
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: commit-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
    profiles:
      - debug

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: commit-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@commitapp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    profiles:
      - debug

volumes:
  postgres_data:
  redis_data:
  mobile_node_modules:

networks:
  commit-network:
    driver: bridge


