services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src:cached
      - ./backend/package.json:/app/package.json:cached
      - ./backend/tsconfig.json:/app/tsconfig.json:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    command: npm run dev

  # Development tools
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: commit-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@commitapp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres


  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: commit-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

